### ISSUE TITLE
Linked Categories rather than Linked Views

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#115]
Ok, this is a game changer ... and perhaps far too late in the cycle.

But while The LinkedView started out in the People category & shifted to the Relationships category, it actually evolved beyond a single view mode. It turned into a dynamic category navigator. More dynamic than anything else in Gramps.

Unlike other view modes, the LinkedView simultaneously changes Category and object focus. The original Relationship view mode changes the object focus in an inactive (People) view... but you have to navigate Categories to drill down to that. LinkedView actually layered in a direct one-step method of coordinated movement through the categories AS the focus snaps to a new object.

I think you already envisioned this since you asked Barrie for Linked themed icons in multiple categories.

To make the the shift of the outer Category shifting less disorienting... Changing object types should actually change category in the Navigator sidebar & the view mode in the Toolbar to match the object's Category.

Then the Toolbar & menu repopulation becomes expected rather than disorienting.

It would take some planning to make the registration work. (You'd have to register icons & help_url for each Category.  But, based on the amalgamated Rules registrations, I think it can all be done in a single .gpr.py file.)

The other ugliness is that it would need a failback for when the LinkedView in the destination category has been removed/disabled (via the Plugin Manager or manually) so that it still changes object focus AND Category... but falls back to whatever the last used mode was in that category.

The only Categories that would lack a dedicated LinkView would be: Dashboard, Charts, Geography. 

The Relationships vs. People inheriting the current LinkedView is arguable.  You could:
1) add a variants to both categories while considering them different scopes of similarly arranged data (Person would ignore the extended family in the Timeline, Citations, etc.), or
2) add a scope switch to a Person LinkedView & look to the future... by reserving the Relationships LinkedView for future expansion. 

(The categories not currently having a LinkedView could be reserved for future implementation where such a View mode would add perspective to the linkages in that category.

Relationship linkages... somehow amalgamating but differentiating explicit & implicit linkages, Family vs Association, Note links or Tag, source-linked, citation-linked or Place-linked connections. 

Similarly, a future Charts LinkedView might feed some clustering data to yEd. A person clustering dataset for a source might arrange People by page number or quantity of citations. 

A Geography LinkView might call something like Matt Kemmer's Heatmap webreport.)

**Comment by cdhorn** [comment]
> ... and perhaps far too late in the cycle.

Not really.  While I want to get something out soon I don't have any deadline driving me.

> Unlike other view modes, the LinkedView simultaneously changes Category and object focus.

Yes, the category focus shifting has worked that way from very early on. Some Gramplets I'm sure have trouble with that.

> I think you already envisioned this since you asked Barrie for Linked themed icons in multiple categories.

No, I asked for those because it treats most reference objects as something in their own right. Today the stock link icon is used in Gramps to represent all of them and I thought it might be nice to have more specific icons available. All except the PlaceRef have a corresponding page view so you can navigate to them and view notes and citations associated with them.  

In some sense that isn't as necessary since I added the child object group windows support but that was done before I realized I should add the indicators and the external window support to view them. Realize I didn't approach things with a finished design in mind, I sort of felt my way through it as it evolved.

> Changing object types should actually change category in the Navigator sidebar & the view mode in the Toolbar to match the object's Category.

It could possibly be done that way but I don't like the thought of having the view registered separately in every category. 

Also when you switched it would need to not just switch category but switch the active view in that category which I don't see as desireable. I'm also not sure Gramps core has the code needed for it to do that. 

Another approach would be to make it it's own category. In my mind that would be cleaner and is something I've been meaning to look at as well. Maybe I will dig around a little today to see how that is done. 

@Nick-Hall if you can spare a little time could you pull the latest version of this and navigate a bit and let me know your thoughts and which of those two approaches you want to see?

**Comment by cdhorn** [comment]
Oh that was trivial to do, I didn't realize the category could be anything we want in the .gpr file!

Now why didn't it render the icon...

**Comment by cdhorn** [comment]
Browseable might be a good category name.

**Comment by emyoulation** [comment]
> Another approach would be to make it it's own category. In my mind that would be cleaner and is something I've been meaning to look at as well. Maybe I will dig around a little today to see how that is done.

A previous inquiry to Serge indicated that the add-on framework does _**NOT**_ extend to adding entire new categories.

The disorientation I mentioned before might be amplified by gathering all these view modes pages into a category. Right now, the categories disambiguate what will appear in the main view. Having the Navigator shift focus means the highlighting of the type of object that is in focus will alleviate the disorientation a bit further.

But having similar content in an amalgamated category would not only obfuscate the GUI path to similar functionality, but make the user drill down to discover an option even exists. The category named "Places" has obvious purpose and draws people interested in that data. "Linked" is too great of an abstraction to create the same "call to action" and narrowing of focus.

**Comment by emyoulation** [comment]
> Browseable might be a good category name. Any others come to mind?

Still pretty abstract. But it also carries the conceptual baggage of a Internet Browser. They might expect a data scraping (and potentially, a compare/merge) dual view.

**Comment by cdhorn** [comment]
> The reply to a previous inquiry to Serge indicated that the add-on framework does NOT extend to adding entire new categories.

Not sure about that, seems to work fine.  gramps.gui.navigator shows if no icon found in the pre-defined CATEGORY_ICON dictionary it defaults to the gramps-view icon which explains that.

The view-categories option in gramps.ini defines the ordering of the built in categories. Others get appended at the bottom of the sidebar.

**Comment by emyoulation** [comment]
I've tried the additional Category and have 2 reasons why it feels like the wrong direction:

* You cannot leverage all the add-on Gramplets that are category specific & would give you view modes more context. <br />_As when the LinkedView was a **Relationships** category view mode, such Gramplet caveats are an indicator that the feature has an anomalous placement in the GUI metaphor._
* the Navigator highlighting provides no refining of context. It actually strips context away from the view modes.

**Comment by cdhorn** [comment]
Closing this as the refactor has broken the view apart so it spans categories.
