### ISSUE TITLE
Future Feature? Add "About CardView" entries to all context menus.

### ISSUE THREAD

**Issue by fxtmtrsine** [cdhorn/CardView#162]
Add "**About CardView**" or "**About Card View**"@ entries to all context menus that link to:

https://gramps-project.org/wiki/index.php/Addon:CardView

Like shown in the Graph View/Timeline pedigree/Htreeview addons eg:

![37261398-3ab5b49c-25f0-11e8-8dba-b3e4b81fadf9](https://user-images.githubusercontent.com/32380545/170847666-b7048f45-dd25-4fd5-abf7-c7385458d6e2.png)

* Naming the link  "**About Card View**"* with a space between the words would allow for better translation, as it helps add context if you do this then I also suggest adding the word(s) "Card"/"Card View" to the tooltip of each card view icon eg: "Family Card View"  
 
![](https://user-images.githubusercontent.com/32380545/170847816-96b3b556-1a25-4ecb-8e09-999fe62588c3.png)

@ this will also help differentiate if people are reporting issues down the line and help with documentation and searching for it?

Same with the existing help text on the lifesaver icon:
![](https://user-images.githubusercontent.com/32380545/170847973-cbb527fc-83c0-4f32-bf28-943f72863cf4.png)

possibly change it to "About Card View" also as it only goes to the top level of the page and not a context section of the help.

**Comment by emyoulation** [comment]
Clicking the life preserver/buoy will take the user directly to help on the feature. (Since this add-on is pre-beta, docs are still in development.)

This add-on & [Lifelines chart](https://gramps-project.org/wiki/index.php/Addon:Life_Line_Chart_View) add-on are the only view to integrate a Help button in their GUI. So it is not surprise that you did not look for it.

Increasing the specificity of label for the view mode icon has ugly consequences in the Navigator bar & Toolbar. You might have noticed the problem in Geography view.  Overly verbose label mean fewer icon fit on a labeled toolbar an Navigator sidebar. Notice how much screen real-estate is wasted in the Geography view Navigator:

https://gramps-project.org/wiki/images/7/72/GeographyCategory-AllKnownPlacesForOneFamily-example-50.png
But re-labeling the rollover hint for the Help would be good.

**Comment by cdhorn** [comment]
Help toolip now Card View help

**Comment by wroldwiedbwe** [comment]
> Add "About CardView" or "About Card View"@ entries to all context menus that link to:

Great idea 👍 

The Gramps help system probably needs an overhaul!
