### ISSUE TITLE
Nav Gramplet does not shift focus if the Cardview view mode for that category is active

### ISSUE THREAD

**Issue by emyoulation** [cdhorn/CardView#163]
In the example.gramps tree
open the Person CardView mode
undock/detach the "Recent Changes" Gramplet
   (this issue also occurs with it docked but the flexibility of undocked offers more testing options)
Switch to the People view mode
   clicking on the various people in the Recent Changes mode correctly shift the focus of the View mode
Switch back to the Person CardView mode
   clicking on the various people in the Recent Changes mode incorrectly cannot shift the focus

It appears that the Active Record focus only changes if the View Mode or Category also changes.

**Comment by cdhorn** [comment]
Per #137 there are still navigation issues to sort.  And I thought I almost had it but then the RestoreHist Gramplet makes some assumptions about things and it breaks that.

**Comment by cdhorn** [comment]
Oh you undocked it too... hmm... I had not considered that, that may further complicate things...

**Comment by cdhorn** [comment]
Pretty sure I have things sorted okay now in latest push. Let me know if you think otherwise.

NOTE: You will see warning in console:

Warning: GlobalHistory: Signal emitted with wrong arg types: active-changed
         from: file: /home/cdhorn/.gramps/gramps51/plugins/RestoreHist/restorehist.py
               line: 59
               func: clear_history
    arg passed was: ['', ''], type of arg passed <class 'list'>,  type should be: <class 'tuple'>

This is okay, though it would be nice for RestoreHist to handle it cleanly.  Issue is json.dumps converts tuple to a list but it doesn't get converted back on load. I emailed Paul to see if he has any suggestions short of updating the RestoreHist addon.

**Comment by cdhorn** [comment]
Closing this with 3c4ed2a4a4629b82dbe39c102466c69bfd47e591 now.

Left click should always go to the card view, middle click should always go to list view, right click edit.
