### ISSUE TITLE
Issues with new last changed view.

### ISSUE THREAD

**Issue by PQYPLZXHGF** [cdhorn/CardView#210]
> The last changed gramplet has been converted into a dashboard view to complement the statistics one.

I like that it is a view, the only things I'll note are:
* that now it is only a view and I'm no longer able to detach it like a gramplet and have it over to side of the screen :(
* on the dashboard the icons are identical for each view
* on the dashboard the the first icon is now the changes view instead of the statistics view!
* on the changes for repositories I'm seeing a lot of spaces instead of a single line per result?

Maybe consider including both the gramplet version and the dashboard view? 

![2022-09-04 15_26_57-Example gramps - Changes - Gramps](https://user-images.githubusercontent.com/212355/188298836-57cdb98d-ab19-4c8d-94f2-abc2b71cf101.png)

[mentioned on closed issue](https://github.com/cdhorn/CardView/issues/196#issuecomment-1236262377)

**Comment by cdhorn** [comment]
You can use pin copy of current view to spin a copy off in another window.  That is the icon next to the refresh statistics button next to the life buoy help icon.

At moment I don't have a different icon for the last changed view for the tool bar.

For the repository issue are you on Windows?

**Comment by emyoulation** [comment]
Yes.  I can reproduce it on Windows.   
The Categories of the Changes Dashboard view mode that have extra blank rows are:
   Sources, Repositories, Media (slightly tighter), and Tags (REALLLLY fat)
The Categories that are OK are:
   People, Families, Events, Places, Events, Notes

**Comment by cdhorn** [comment]
Thanks, yeah I will need to spin up a VM and check it out.

**Comment by TheMihle** [comment]
How tall the boxes are depens on how many items it is showing, it seems like its programmed to use a spesific amount of height no matter the amount of items or something?
As I have only created one tag yet(Probably should have had more), so its _**Really fat**_:
![bilde](https://user-images.githubusercontent.com/32242447/194620404-a9cdc0f7-d947-4751-9e3c-61d5de4cb43f.png)

Also, it seem to show 20 items max, is it possible to adjust that or what spesific height it always uses so it can use more height? Because on my high res monitor, there is a lot of empty space, that could have been used to show more items:

![bilde](https://user-images.githubusercontent.com/32242447/194622013-85235649-504c-4bb2-b6e1-7cf0bb633ec7.png)

(I should really work more on my tree than playing around with plugins and stuff, but its fun and helpful so maybe not)

**Comment by emyoulation** [comment]
> > The last changed gramplet has been converted into a dashboard view to complement the statistics one.
> 
> I like that it is a view, the only things I'll note are:
> 
>     * that now it is only a view and I'm no longer able to detach it like a gramplet and have it over to side of the screen :(
>  
> Maybe consider including both the gramplet version and the dashboard view?
> 
> [mentioned on closed issue](https://github.com/cdhorn/CardView/issues/196#issuecomment-1236262377)

For a 'detached' view, you can use the "Pin Copy" toolbar feature. It is locked from Navigating but it updates and responds to Preference template changes.

**Comment by cdhorn** [comment]
Expansion issue on windows fixed.

Global -> Display -> Maximum items per changed object list can be tuned from 1 to 40 now with 20 default.
